# Generated by Django 5.0.6 on 2024-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_blog_table_blog_rename_comment_table_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='explore/'),
        ),
    ]
