# Generated by Django 5.0.6 on 2024-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(default='visible', max_length=20),
        ),
    ]
